# Generated by Django 3.2 on 2022-11-01 15:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('short_description', models.TextField(blank=True, default=None, verbose_name='Краткое описание новости')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Содержимое новости')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_private', models.BooleanField(blank=True, default=False, verbose_name='Приватная новость')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
