# Generated by Django 3.2 on 2022-11-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_new_image_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='description',
            new_name='content',
        ),
    ]
