from django.http import HttpResponse
from .utils import *
from django.views.generic import View
from .appviews.Register import *
from .appviews.HomePage import *
from .appviews.New import *
from .appviews.About import *
from .appviews.CreateNew import *
from .appviews.EditNew import *